FROM python:3

# use apt to install
RUN apt-get update;\
    apt-get install -y curl

WORKDIR /usr/src/app

ADD requirements.txt .
# install python module
RUN pip install -r requirements.txt

ADD backend .

EXPOSE 8800
CMD ["python3", "manage.py", "runserver", "0:8800"]
